### ISSUE TITLE
Add cURL code generation capability

### ISSUE THREAD

**Issue by bobby-brennan** [kaltura/developer-platform#1]
Add code generation for cURL [reference](https://github.com/kaltura/kaltura-api-recipes/issues/5). Note that with cURL the global format parameter should show in the sample code (unlike other   languages, here it is usable and can be set).

**Comment by jessp01** [comment]
Was implemented && deployed.

**Comment by zoharbabin** [comment]
@jessp01 / @bobby-brennan - is this confirmed? can we move it to the done column?
