### ISSUE TITLE
Make cURL the default language, and save language preference in cookie

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/developer-platform#23]
Once cURL codegen (#1) is added, make it the default language (if the user didn't select a language yet). If the user changed the language, store it in a cookie and load it as default instead.

**Comment by jessp01** [comment]
Implemented && deployed.

**Comment by zoharbabin** [comment]
@jessp01 / @bobby-brennan - is this confirmed? can we move it to the done column?

**Comment by jessp01** [comment]
Yup. Site's already updated.
