### ISSUE TITLE
Create a new homepage design that will focus quick start for newcomers

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/developer-platform#24]
Update the homepage (the page seen when visiting the base url; developer.kaltura.com) to be friendlier to new comers.
See early sketch here - [Developer Homepage[1].pdf](https://github.com/kaltura/developer-platform/files/1814424/Developer.Homepage.1.pdf)

**Comment by zoharbabin** [comment]
Waiting for design to complete before assigning to @bobby-brennan .
@tzubeli will update this and re-assign once the design is ready.

**Comment by bobby-brennan** [comment]
@zoharbabin still need videos for the HTML5 Video Player section. I think that's the last TODO though.

**Comment by jessp01** [comment]
@zoharbabin, @tzubeli, can this be closed?
Thanks,
