### ISSUE TITLE
Add a new section for Web Player and Mobile Player SDKs (just like API-docs)

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/developer-platform#25]
This section will feature the downloads, github links, demonstrations, and documentation pages.

@AnnaAleksandrowicz, @OrenMe and @itaykinnrot - assigning to you to help define how and what we'd like to have before we assign to @bobby-brennan for development.

**Comment by AnnaAleksandrowicz** [comment]
Just to clarify, we'll have all the TV Platform Player info on the OTT site, correct? Will that be OK for OVP?

**Comment by jessp01** [comment]
Hi @AnnaAleksandrowicz,

OTT has its own dedicated site [ott.developer.kaltura.com] with content that is relevant to it and is irrelevant to OVP.
There is, of course, a common code base developer.kaltura.com and ott.developer.kaltura.com share but the docs, download links, etc, are different.

**Comment by bobby-brennan** [comment]
Any progress here? We can remove the "Player" link from the navbar if this won't be ready for launch on June 10.

**Comment by zoharbabin** [comment]
Yes, let's hide it for now, we'll launch without Player. And add it at a later date.
Thanks!

**Comment by jessp01** [comment]
Was added.
