### ISSUE TITLE
Update code generation for Kaltura's new NodeJS SDK

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/developer-platform#28]
There were updates to the NodeJS SDK. Updates are required to the codegen.
@tan-tan-kanarek - please advise on the details of what needs to be updated.

@AnnaAleksandrowicz - please note in case we need to update any docs.

**Comment by tan-tan-kanarek** [comment]
The new client lib has different structure, static services, request builder execution, different callback and so on.

**Comment by jessp01** [comment]
@bobby-brennan -  please use https://github.com/kaltura/KalturaGeneratedAPIClientsNodeJS/blob/13.16.0/test/media.js as reference.
