### ISSUE TITLE
Use 12px for body monotype font

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/developer-platform#30]
Overall we should use a smaller font size for default body monotype font. Let’s switch to 12px like the old testme console.

**Comment by bobby-brennan** [comment]
You're talking about the code samples like on [this page](https://developer.kaltura.com/api-docs/VPaaS-API-Getting-Started/how-to-create-kaltura-session.html/), right? We could also change the size of the sample code in the API console and workflows

**Comment by jessp01** [comment]
@zoharbabin - I didn't see a reply to Bobby's question [https://github.com/kaltura/developer-platform/issues/30#issuecomment-373447232]... Are you satisfied with how it looks here? https://developer.kaltura.com:8443

**Comment by zoharbabin** [comment]
@bobby-brennan yes, everywhere we have code it should be the same font and size.

thanks!

**Comment by bobby-brennan** [comment]
Fixed in f20667ae0f5a183d1a1f84a27ee36fded1e57d89

**Comment by jessp01** [comment]
Confirmed.
