### ISSUE TITLE
Fix search behavior

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/developer-platform#31]
Update the Search behavior to: 

- Search should also search inside the docs and not just based on titles/metadata.
- Do not show duplicate items in the 

Consider using SwiftType (account details provided privately) as search API when online... BUT, need to carefully consider how we deal with offline (if user using docs and is not connected) and multiple schema versions.

**Comment by bobby-brennan** [comment]
What do you mean by "offline"? You need to be online to load the page...

For multiple schema versions, I think the best thing to do is have multiple swiftype engines.

**Comment by zoharbabin** [comment]
Offline, as in when the system is not on kaltura.com, but on a self-hosted environment where SwiftType isn't available... can we gracefully degrade to local search?

**Comment by jessp01** [comment]
SwiftType implementation is in place and works. @bobby-brennan - did you implement the suggestion you made in your last comment?

**Comment by bobby-brennan** [comment]
You can now set DISABLE_SWIFTYPE=true when running lucybot build

Bobby Brennan
bobby.brennan@gmail.com
