### ISSUE TITLE
Show boolean parameters as a true/false dropdown or toggle

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/developer-platform#37]
Currently boolean params are text input... please change to true/false dropdown or toggle button.

**Comment by jessp01** [comment]
@zoharbabin,

Do you mean in the workflow editor? If so, indeed, if the param being added is of type ```bool```, like upload.finalChunk for instance:
```
<param name="finalChunk" type="bool" optional="1" default="true" description=""/>
```

Then the editor should render a selectbox representing this input, not a textbox.

When rendering a workflow step [form], this is already supported, see ```finalChunk``` here:
https://developer.kaltura.com/workflows/Ingest_and_Upload_Media;step=2

This is annotated like so:
```
      "name": "finalChunk",
      "enum": [
        true,
        false
      ],
```

**Comment by zoharbabin** [comment]
I referenced the Console.
Good to know it is solved in Workflows, but should behave the same in Console too.
