### ISSUE TITLE
Configure versions support for the ott site

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/developer-platform#38]
Configure the site to load multiple schemas. (feature is already available, this only needs to be configured).

@tan-tan-kanarek - let us know if you need any further assistance or changes for this.

**Comment by tan-tan-kanarek** [comment]
How is it should be configured?

**Comment by bobby-brennan** [comment]
Here's the docs: http://docs.lucybot.com/LucyBot_yml/API_Specifications

See the "Versions" section. Let me know if you have any trouble.

**Comment by zoharbabin** [comment]
@tan-tan-kanarek - can we close this ticket?

**Comment by tan-tan-kanarek** [comment]
No, I didn't have the time to test it yet, sorry.

**Comment by tan-tan-kanarek** [comment]
Same as https://github.com/kaltura/developer-platform/pull/56, becoming irrelevant, I won't spend time on it.

**Comment by zoharbabin** [comment]
Closing, if becomes relevant please re-open.
