### ISSUE TITLE
Relative path for multiple schemas

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/developer-platform#39]
Support relative path in order to place entire system under sub directory, e.g.   https://ott.developer.kaltura.com/v4.7/ or http://customername.com/staging/

@bobby-brennan - you mentioned this is easily doable. Can you please share details on how?

**Comment by jessp01** [comment]
You just need to set the basePath option when building the site: http://docs.lucybot.com/LucyBot_yml.

**Comment by jessp01** [comment]
Hi @tan-tan-kanarek,

Did you try?

**Comment by tan-tan-kanarek** [comment]
Not yet.

**Comment by tan-tan-kanarek** [comment]
It's working as expected.

**Comment by tan-tan-kanarek** [comment]
@bobby-brennan , for some reason the basePath doesn't affect the generated html anymore.
See the branch I used: https://github.com/kaltura/developer-platform/blob/ott-versioned/ott.LucyBot.yml

**Comment by jessp01** [comment]
@bobby-brennan - documentation-generator#d26f2a2 was used.

**Comment by bobby-brennan** [comment]
Thanks for the report, looks like we lost it when updating AngularJS. Fixed in https://github.com/LucyBot-Inc/documentation-generator/commit/87554da20b3a94f9ba15e3f124ab5aff1d522ad0

**Comment by jessp01** [comment]
Thanks @bobby-brennan. @tan-tan-kanarek - can you please update and let us know?

**Comment by tan-tan-kanarek** [comment]
Updating to this new version didn't help.

**Comment by tan-tan-kanarek** [comment]
@bobby-brennan, does it work for you?

**Comment by bobby-brennan** [comment]
Yes, this works fine for me. I don't see basePath in ott.LucyBot.yml - are
you working from that file in developer-platform?

Bobby Brennan
bobby.brennan@gmail.com

**Comment by tan-tan-kanarek** [comment]
Exists here:
https://github.com/kaltura/developer-platform/blob/ott-docker/ott.LucyBot.yml
and here:
https://github.com/kaltura/developer-platform/blob/ott-versioned/ott.LucyBot.yml

T.

**Comment by jessp01** [comment]
Hi @tan-tan-kanarek - is there still a problem or can we close this issue? Thanks.

**Comment by tan-tan-kanarek** [comment]
Solved, thanks.
