### ISSUE TITLE
Performance optimizations to page loading times

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/developer-platform#41]
The system needs a much much much faster page loading times, it currently loads too slowly.

Please look into performance optimizations, including: 

- Ahead-of-time compilation
- Pre-rendering
- On-demand loading of the OpenAPI document

**Comment by jessp01** [comment]
Several optimisations were put in place. @bobby-brennan - loading time was indeed decreased and I feel we're in a much better place. Would be good, however, for future reference, if you could provide a high level description of the optimisations done.

Thanks,

**Comment by bobby-brennan** [comment]
The main change was switching from Angular's JIT compiler to AOT compiler, which reduces bundle size. We also moved to the official Angular Universal project for prerendering, rather than doing prerendering ourselves inside of PhantomJS
