### ISSUE TITLE
Update URL structure for better SEO

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/developer-platform#43]
Direct Action URL –  Urls shows be replaced to be of the structure: domain/apidocs/service/x/action/y . It is fairly descriptive and also short enough to render fully in the Google search result. 

https://www.youtube.com/watch?v=AQcSFsQyct8 explains underscores vs. hyphens. 

In our case since underscores literally are the name of the API, it actually does make sense to continue using underscores. 

However, we should stop using hash (#) because these are used to indicate fragments on the page   (and in fact something we do want to support, deep link inside the page and having Google index these fragments).

**Comment by bobby-brennan** [comment]
Where are you seeing `#` used?

**Comment by zoharbabin** [comment]
I think we're no longer using hash signs... great!
But, we do use `;` - like here: https://developer.kaltura.com/workflows/Secure_Control_and_Govern/Group_Management;step=3

Can we make step be `/` (like `/step/3`) or is it too complex / hurt performance?

**Comment by jessp01** [comment]
Why not pass the step as a simple GET param? i.e "?step=3"

**Comment by bobby-brennan** [comment]
It's an angular-specific quirk.

Bobby Brennan
bobby.brennan@gmail.com

**Comment by jessp01** [comment]
@bobby-brennan - I admit that I'm not, by any means, an Angular JS expert. In fact, I've never seriously used it for anything:) That said, can you please explain further? Looking here:
https://docs.angularjs.org/api/ngRoute/service/$routeParams
https://docs.angularjs.org/api/ng/service/$location#search

I see "?" is used, as you'd expect.

**Comment by bobby-brennan** [comment]
Those are the Angular 1 docs - here's the latest documentation
<https://angular.io/guide/router>:

The id value appears in the URL as (;id=15;foo=foo), not in the URL path.
The path for the "Heroes" route doesn't have an :id token.

The optional route parameters are not separated by "?" and "&" as they
would be in the URL query string. They are *separated by semicolons ";"* This
is *matrix URL* notation — something you may not have seen before.

*Matrix URL* notation is an idea first introduced in a 1996 proposal
<http://www.w3.org/DesignIssues/MatrixURIs.html> by the founder of the web,
Tim Berners-Lee.

Although matrix notation never made it into the HTML standard, it is legal
and it became popular among browser routing systems as a way to isolate
parameters belonging to parent and child routes. The Router is such a
system and provides support for the matrix notation across browsers.

The syntax may seem strange to you but users are unlikely to notice or care
as long as the URL can be emailed and pasted into a browser address bar as
this one can.


Bobby Brennan
bobby.brennan@gmail.com

**Comment by jessp01** [comment]
Hey Bobby,

Yes, I'm familiar with the Matrix URL notation.
Didn't realise it's the standard for Angular JS based apps, however.

Anyhow, seeing how it is and considering there's no technical issue here, I don't think we've got anything to address.

@zoharbabin - I think we can close the issue.

**Comment by bobby-brennan** [comment]
Fixed the `;apiCall=foo.bar` links to be standard SEO-friendly links.
