### ISSUE TITLE
Enums selectboxes should be displayed with the actual value in brackets

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/developer-platform#48]
Where there is a selectbox with enums, their names should be displayed with the actual value in brackets. for example:

- EXACT_MATCH (1)
- PARTIAL (2)
- STARTS_WITH (3)
- EXISTS (4)
- RANGE (5)

As opposed to now where only the literal value populates the selectbox.

**Comment by jessp01** [comment]
Implemented.
