### ISSUE TITLE
Remove Categories from the Console menu

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/developer-platform#51]
If the user goes to the console, they already know what they're looking for, so the categories aren't needed and are actually somewhat confusing/time consuming.
Here we should just present a flat view of services.

@tzubeli / @jessp01 - FYI

**Comment by bobby-brennan** [comment]
@zoharbabin do you just want to show the services in alphabetical order?

We can also continue grouping by category, but auto-expand the categories.

**Comment by bobby-brennan** [comment]
@zoharbabin Here's how this looks now:

![image](https://user-images.githubusercontent.com/7611973/38272440-2e28f784-3757-11e8-90ed-7d1627172ee1.png)
