### ISSUE TITLE
Ability to annotate services and actions as beta was added to the client generator

### ISSUE THREAD

**Issue by jessp01** [kaltura/developer-platform#54]
See https://github.com/kaltura/clients-generator/pull/293/files

Following that, the "beta" attribute should be inspected when parsing the API schema.
If set to true, the behaviour should be exactly the same as with the ```deprecated``` attribute only the message should be:
"Please note: this <SERVICE_NAME/ACTION_NAME> is experimental."

**Comment by bobby-brennan** [comment]
Is this in the current API schema anywhere? I don't see any `beta` tags in http://www.kaltura.com/api_v3/api_schema.php

**Comment by jessp01** [comment]
Hi @bobby-brennan - yes, that's the latest but no service is yet marked as beta...

**Comment by jessp01** [comment]
Implemented.
See https://developer.kaltura.com:8443/api-docs/service/liveStream/action/allocateConferenceRoom for example.
