### ISSUE TITLE
workflows/Ingest_and_Upload_Media - not all langs are available

### ISSUE THREAD

**Issue by jessp01** [kaltura/developer-platform#59]
See https://developer.kaltura.com:8443/workflows/Ingest_and_Upload_Media;step=1 [and also step=2] which points to an instance deployed with the latest from the master branch.

Only available langs in the select box are:
- PHP
- NodeJS
- Ruby
- JS

In step 3, this is no longer the case.

**Comment by bobby-brennan** [comment]
Fixed here: https://github.com/kaltura/developer-platform/commit/00ffc967359aea4efbed63cbbd82a356f1c41e5a

**Comment by jessp01** [comment]
Confirmed. Thanks.
