### ISSUE TITLE
workflows/Ingest_and_Upload_Media;step=2 fails when using Firefox

### ISSUE THREAD

**Issue by jessp01** [kaltura/developer-platform#60]
After submitting the form in step 2, the `uploadToken.upload()` request fails with:
```json
{
  "code": "UPLOAD_TOKEN_INVALID_STATUS_FOR_UPLOAD",
  "message": "Upload token is in an invalid status for uploading a file, maybe the file was already uploaded",
  "objectType": "KalturaAPIException",
  "args": []
}
```
Can be reproduced here: https://developer.kaltura.com:8443/workflows/Ingest_and_Upload_Media;step=2

This works correctly when using Chrome. @bobby-brennan - sent you a HAR file by mail. 

I'm using Firefox 60.0 but I believe it will reproduce with other versions as well.

**Comment by jessp01** [comment]
@bobby-brennan - have you got an update on this one? Thanks.

**Comment by bobby-brennan** [comment]
I've been unable to reproduce using Firefox on OSX. Is this still
happening? Can you confirm with multiple accts?

Bobby Brennan
bobby.brennan@gmail.com

**Comment by jessp01** [comment]
When it happened, it happened with all account which makes sense seeing how it was a clearly a browser specific issue [it always worked in Chrome, as per my original description].

I can't reproduce it at the moment however, so it must have been fixed somewhere along the way. Closing..
