### ISSUE TITLE
Create a codegen for the TypeScript Client Library

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/developer-platform#61]
As per the discussion at https://github.com/kaltura/developer-platform/issues/50 - the TypeScript client is also ready to be released. Let's create a codegen for.

@bobby-brennan - units for this client can be found here:
https://github.com/kaltura/KalturaGeneratedAPIClientsTypescript/tree/master/src/tests

**Comment by bobby-brennan** [comment]
Sounds good. This looks like an additional 4 hours of work - is that good with you?

**Comment by KalturaCommunity** [comment]
Yes

**Comment by zoharbabin** [comment]
@bobby-brennan - Yes, let's please implement.

**Comment by bobby-brennan** [comment]
Implemented in 25516874f930d978c7f3c73cf0d2f1309abdaab3
