### ISSUE TITLE
On lucyBot build get the workflows directory from config

### ISSUE THREAD

**Issue by tanyaLibatter** [kaltura/developer-platform#78]
create a subfolders in 'workflows' folder one for ovp and one for ott- which will contain all the workflows for ovp and other for the ott.
Allow to configure the path of workflows folder and use it in addWorkflows function in lucyBot build script instead of using hardcoded folder name which is 'workflows'

**Comment by bobby-brennan** [comment]
We've now got a `workflowDirectory` setting that can be put in the top-level of LucyBot.yml - does that solve the issue?

**Comment by tan-tan-kanarek** [comment]
Yes, thank you.

**Comment by tan-tan-kanarek** [comment]
@tanyaLibatter, please test and verify it's working as you need it.

**Comment by tanyaLibatter** [comment]
@tan-tan-kanarek  - configured and verified with lucyBot v4.4.0.
@jessp01 / @bobby-brennan - please review https://github.com/kaltura/developer-platform/pull/79

**Comment by zoharbabin** [comment]
@bobby-brennan and @jessp01 - Can you please advise on this ticket's status?

**Comment by jessp01** [comment]
#79 was merged a while back.
