### ISSUE TITLE
issue with  edit / create workflows

### ISSUE THREAD

**Issue by tanyaLibatter** [kaltura/developer-platform#93]
Following this issue: https://github.com/kaltura/developer-platform/issues/78 which was implemented in lucyBot v4.4.
While trying to save or load a workflow getting http 404 error since load workflow path is wrong – currently the path lucyBot using is workflows/${workflowName}  but since the path to workflows is configurable it should be taken from  workflowDirectory setting  (/${workflowDirectory }/${workflowName}).
 
This issue prevents us from edit / create workflows in order to solve changes in lucyBot required.

**Comment by AnnaAleksandrowicz** [comment]
@bobby-brennan - Bobby this is a showstopper for our site so if we really need to fix it ASAP.

**Comment by bobby-brennan** [comment]
Can you confirm which version of LucyBot you're on? This is for OTT correct?

I'm a bit swamped today, but if it's an easy fix I will try and get to it ASAP.

**Comment by AnnaAleksandrowicz** [comment]
Checking re: version and yes, OTT.
If we get this fixed by EOW that would be awesome...

**Comment by AnnaAleksandrowicz** [comment]
Bobby we're guessing 4.4 - but I don't have access to the server (neither does Tanya) so we're not 100% sure.

**Comment by bobby-brennan** [comment]
Please try updating to latest (`4.6.11`) - I think it's fixed there

**Comment by AnnaAleksandrowicz** [comment]
@tan-tan-kanarek and @tanyaLibatter  - is it possible to update our version to 4.6.11? This should fix the problem.

**Comment by tan-tan-kanarek** [comment]
We can

**Comment by tanyaLibatter** [comment]
@bobby-brennan Before installing it on server I want to verify that it works on my local env but unfortunately one of lucybot dependencies is node-sass v3.13.1 this version does not supports my os (macOS Mojave), is it possible to update the node-sass version in package.json  to newer lets say ^4.9.0?

**Comment by bobby-brennan** [comment]
Hi Tanya,

I updated to `node-sass@4.11.0` in `lucybot@4.8.3` - let me know if you see any problems.

**Comment by tanyaLibatter** [comment]
Hi @bobby-brennan ,

I installed the new version of lucybot, looks much better and 404 error is fixed but I still was not able to make the git authentication:
after I clicked log into gitHub button - I always redirected to https://developer.kaltura.com/oauth_callback.html - is it possible to configure the host name?

And another question regarding the BE Url:
 currently the BE host is taken from an ott.openapi.json (host property)- is it possible to take the BE host URL from environment variable 
(we are running the docs portal on more than one environment) ?

**Comment by bobby-brennan** [comment]
Hi Tanya,

You can set up your own GitHub OAuth client to handle authentication.
You'll need to set the GITHUB_CLIENT_ID and GITHUB_CLIENT_SECRET
environment variables when starting the server. You'll also need to edit
ott.LucyBot.yml and add:

github:
  repo: "kaltura/developer-platform"
  client_id: "YOUR_CLIENT_ID"
  access_token_url: "/github/access_token"
  redirect_uri: "PATH_TO_BASE_SERVER/oauth_callback.html"

Make sure that redirect_uri is the same as in your GitHub OAuth client
settings.

Hope that helps!

Bobby Brennan
bobby.brennan@gmail.com

**Comment by jessp01** [comment]
This is also documented in the README and I believe the OTT team already has this working. Closing
